const BannerActionTypes = {
    CLOSE_BANNER: "CLOSE_BANNER",
    PASSWORD_CHANGE_SUCCESS: "PASSWORD_CHANGE_SUCCESS",
    PASSWORD_CHANGE_ERROR: "PASSWORD_CHANGE_ERROR",
    GENERIC_MSG: "GENERIC_MSG"
};

export default BannerActionTypes;
