query {
  UserMyself {
    assignments {
      totalCount
      results {
        id
        name
        descriptionHtml
        submissions {
          results {
            correction {
              id
              score
              createdAt
              data
            }
          }
        }
      }
    }
  }
}
