{
  UserMyself {
    id
    firstName
    lastName
    email
    assignments {
      totalCount
    }
    dateJoined
    ipAddress
    isActive
    isStaff
    isSuperuser
    username
    courses {
      totalCount
    }
    parallels {
      totalCount
    }

    parallelsAsTeacher {
      totalCount
      results {
        name
        course {
          kosTag
        }
      }
    }

    parallelsAsStudent {
      totalCount
      results {
        name
        course {
          kosTag
        }
      }
    }

    # TODO: Fix permissions on backend for this
    # assignments {
    #   results {
    #     score
    #   }
    # }
  }
}
