const UserActionTypes = {
  PASSWORD_CHANGE_SUCCESS: "PASSWORD_CHANGE_SUCCESS",
  PASSWORD_CHANGE_FAILURE: "PASSWORD_CHANGE_FAILURE",
  PASSWORD_CHANGE_ERROR: "PASSWORD_CHANGE_ERROR",
};

export default UserActionTypes;