const FlagActionTypes = {
    DISMISS_FLAG: "DISMISS_FLAG",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_ERROR: "CHANGE_PASSWORD_ERROR",
    ASSIGNMENT_CREATED_MSG: "ASSIGNMENT_CREATED_MSG",
};

export default FlagActionTypes;