const FlagActionTypes = {
    DISMISS_FLAG: "DISMISS_FLAG",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_ERROR: "CHANGE_PASSWORD_ERROR"
};

export default FlagActionTypes;